application/configs/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('log_in/', include('log_in.urls')),
    path('admin/', admin.site.urls),
]

application/log_in/urls.py
from django.urls import path

from . import views

app_name = 'log_in'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('admin/add', views.MyuserCreateView.as_view(), name='add_admin'),
    path('admin/update/<int:id>', views.MyuserUpdateView.as_view(), name='update_admin'),
    path('admin/delete', views.deleteadmin, name='delete_admin'),
    path('admin/profile', views.admin_profile, name='admin_profile'),
    path('admin/activities', views.activities_admin, name='activities_admin'),
    path('adminlist/', views.admin_users_list, name='admin_users_list'),
    path('adminlist/data', views.admin_users_list_data, name='admin_users_list_data'),
    path('user/add', views.UserCreate, name='add_user'),
    path('user/model', views.ModelTrain, name='model_train'),
    path('user/model/train', views.TrainingModel, name='training_model'),
    path('user/model/collect', views.CollectDataset, name='collectdataset'),
    path('user/update/<int:id>', views.UserUpdate, name='update_user'),
    path('user/delete', views.deleteuser, name='delete_user'),
    path('userlist/', views.users_list, name='users_list'),
    path('userlist/data', views.users_list_data, name='users_list_data'),
    path('log_out/', views.log_out, name='log_out'),
    path('password/change', views.password_change, name='password_change'),
    path('password/reset/', views.password_reset, name='password_reset'),
    path('password/reset/update/', views.password_reset_using_token, name='password_reset_using_token'),
    path('adminlog', views.LoginLogss, name='log_in'),
    path('user/home', views.UserLoginPageB, name='userloginpageb'),
    path('', views.UserLoginPageA, name='userloginpagea'),
]

application/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>{% block title %}Gentelella Alela! |{% endblock %} </title>


    <!-- Bootstrap -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/static/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/static/css/nprogress.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="/static/css/animate.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="/static/css/custom.min.css" rel="stylesheet">

{% block extra_css %}{% endblock %}
  </head>
{% block body %}{% endblock %}
</html>

application/templates/profile.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Profile_Layout{% endblock %}</title>

  </head>
  <!-- Bootstrap -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <!-- Font Awesome -->
    <link href="/static/css/font-awesome.min.css" rel="stylesheet">
  <!-- NProgress -->
    <link href="/static/css/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="/static/css/green.css" rel="stylesheet">
    <!-- bootstrap-progressbar -->
    <link href="/static/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
  <!-- JQVMap -->
    <link href="/static/css/jqvmap.min.css" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="/static/css/daterangepicker.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="/static/css/custom.min.css" rel="stylesheet">
    <!-- override this block to add some extra js in head section in children templates -->
    {% block extra_head_js %}{% endblock %}


<body class="nav-md">
<script type="text/javascript">

        function toggleFullScreen() {
            if ((document.fullScreenElement && document.fullScreenElement !== null) || (!document.mozFullScreen && !document.webkitIsFullScreen)) {
                if (document.documentElement.requestFullScreen) {
                    document.documentElement.requestFullScreen();
                } else if (document.documentElement.mozRequestFullScreen) {
                    document.documentElement.mozRequestFullScreen();
                } else if (document.documentElement.webkitRequestFullScreen) {
                    document.documentElement.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
                }
            } else {
                if (document.cancelFullScreen) {
                    document.cancelFullScreen();
                } else if (document.mozCancelFullScreen) {
                    document.mozCancelFullScreen();
                } else if (document.webkitCancelFullScreen) {
                    document.webkitCancelFullScreen();
                }
            }
        }
</script>

{% block profile %}
    <div class="container body">
      <div class="main_container">
          {% block template %}

              <div class="col-md-3 left_col">
              <div class="left_col scroll-view">
                  <div class="navbar nav_title" style="border: 0;"><center>Project on : Face Recognition</center></div>

                <div class="clearfix"></div>
                <br />

                <!-- sidebar menu -->
            {% block sidebar %}
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                  <div class="menu_section">
                    <center><h2>BENNETT UNIVERSITY</h2></center>
                    <ul class="nav side-menu">
                      <li><a href="{% url 'log_in:admin_profile' %}"><i class="fa fa-home"></i>My Profile</a></li>
                      <li><a><i class="fa fa-balance-scale"></i> Admin <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                          <li><a href="{% url 'log_in:admin_users_list' %}">Admin Details</a></li>
                          <li><a href="{% url 'log_in:add_admin' %}">Add Admin</a></li>
                        </ul>
                      </li>
                      <li><a><i class="fa fa-edit"></i> User <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                          <li><a href="{% url 'log_in:users_list' %}">User Details</a></li>
                          <li><a href="{% url 'log_in:add_user' %}">Add User</a></li>
                        </ul>
                      </li>
                    </ul>
                  </div>

                </div>
            {% endblock %}
            <!-- /sidebar menu -->

                <!-- /menu footer buttons -->
                <div class="sidebar-footer hidden-small">
                  <a style="width:50%" onclick="toggleFullScreen()" data-toggle="tooltip" data-placement="top" title="FullScreen">
                    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                  </a>
                  <a style="width:50%" href="{% url 'log_in:log_out' %}" data-toggle="tooltip" data-placement="top" title="Logout">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                  </a>
                </div>
                <!-- /menu footer buttons -->
              </div>
            </div>

            {% block top_navi %}
                <!-- top navigation -->
                <div class="top_nav">
                  <div class="nav_menu">
                    <nav>
                      <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                      </div>

                      <ul class="nav navbar-nav navbar-right">
                        <li class="">
                          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            <img src="images/img.jpg" alt="">Options
                            <span class=" fa fa-angle-down"></span>
                          </a>
                          <ul class="dropdown-menu dropdown-usermenu pull-right">
                            <li><a href="{% url 'log_in:password_change' %}">Change Password</a></li>
                            <li><a href="{% url 'log_in:log_out' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                          </ul>
                        </li>
                      </ul>
                    </nav>
                  </div>
                </div>
                <!-- /top navigation -->
            {% endblock %}
            <div class="right_col" role="main">
              <!-- top tiles -->
                {% block top_tiles %}
              <div class="row tile_count">
                <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                  <span class="count_top"><i class="fa fa-user"></i> Total Users</span>
                  <div class="count">2500</div>
                  <span class="count_bottom"><i class="green">4% </i> From last Week</span>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                  <span class="count_top"><i class="fa fa-clock-o"></i> Average Time</span>
                  <div class="count">123.50</div>
                  <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>3% </i> From last Week</span>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                  <span class="count_top"><i class="fa fa-user"></i> Total Males</span>
                  <div class="count green">2,500</div>
                  <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                  <span class="count_top"><i class="fa fa-user"></i> Total Females</span>
                  <div class="count">4,567</div>
                  <span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>12% </i> From last Week</span>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                  <span class="count_top"><i class="fa fa-user"></i> Total Collections</span>
                  <div class="count">2,315</div>
                  <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                  <span class="count_top"><i class="fa fa-user"></i> Total Connections</span>
                  <div class="count">7,325</div>
                  <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
                </div>
              </div>
          <!-- /top tiles -->
            {% endblock %}


            {% block main_content %}

                  <div class="col-md-6">
                    <h3>Welcome <small>Home Page</small></h3>
                  </div>

            {% endblock %}
        <!-- /page content -->

            </div>
          {% endblock %}
    </div>
    </div>
{% endblock %}


<!-- jQuery -->
    <script src="/static/js/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/static/js/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/static/js/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="/static/js/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="/static/js/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="/static/js/bootstrap-progressbar.min.js"></script>

    <!-- Flot -->
    <script src="/static/js/jquery.flot.js"></script>
    <script src="/static/js/jquery.flot.pie.js"></script>
    <script src="/static/js/jquery.flot.time.js"></script>
    <script src="/static/js/jquery.flot.stack.js"></script>
    <script src="/static/js/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="/static/js/jquery.flot.orderBars.js"></script>
    <script src="/static/js/jquery.flot.spline.min.js"></script>
    <script src="/static/js/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="/static/js/date.js"></script>


<!-- Custom Theme Scripts -->
    <script src="/static/js/custom.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>

      {% block extra_foot_js %}{% endblock %}
</body>
</html>

application/templates/profileuser.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Profile_Layout{% endblock %}</title>

  </head>
  <!-- Bootstrap -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <!-- Font Awesome -->
    <link href="/static/css/font-awesome.min.css" rel="stylesheet">
  <!-- NProgress -->
    <link href="/static/css/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="/static/css/green.css" rel="stylesheet">
    <!-- bootstrap-progressbar -->
    <link href="/static/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
  <!-- JQVMap -->
    <link href="/static/css/jqvmap.min.css" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="/static/css/daterangepicker.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="/static/css/custom.min.css" rel="stylesheet">
    <!-- override this block to add some extra js in head section in children templates -->
    {% block extra_head_js %}{% endblock %}


<body class="nav-md">
<script type="text/javascript">

        function toggleFullScreen() {
            if ((document.fullScreenElement && document.fullScreenElement !== null) || (!document.mozFullScreen && !document.webkitIsFullScreen)) {
                if (document.documentElement.requestFullScreen) {
                    document.documentElement.requestFullScreen();
                } else if (document.documentElement.mozRequestFullScreen) {
                    document.documentElement.mozRequestFullScreen();
                } else if (document.documentElement.webkitRequestFullScreen) {
                    document.documentElement.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
                }
            } else {
                if (document.cancelFullScreen) {
                    document.cancelFullScreen();
                } else if (document.mozCancelFullScreen) {
                    document.mozCancelFullScreen();
                } else if (document.webkitCancelFullScreen) {
                    document.webkitCancelFullScreen();
                }
            }
        }
</script>

{% block profile %}
    <div class="container body">
      <div class="main_container">
          {% block template %}

              <div class="col-md-3 left_col">
              <div class="left_col scroll-view">
                  <div class="navbar nav_title" style="border: 0;"><center>Project on : Face Recognition</center></div>

                <div class="clearfix"></div>
                <br />

                <!-- sidebar menu -->
            {% block sidebar %}
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                  <div class="menu_section">
                    <center><h2>BENNETT UNIVERSITY</h2></center>
                    <ul class="nav side-menu">
                      <li><a href="#"><i class="fa fa-home"></i>My Profile</a></li>
                    </ul>
                  </div>

                </div>
            {% endblock %}
            <!-- /sidebar menu -->

                <!-- /menu footer buttons -->
                <div class="sidebar-footer hidden-small">
                  <a style="width:50%" onclick="toggleFullScreen()" data-toggle="tooltip" data-placement="top" title="FullScreen">
                    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                  </a>
                  <a style="width:50%" href="{% url 'log_in:userloginpagea' %}" data-toggle="tooltip" data-placement="top" title="Logout">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                  </a>
                </div>
                <!-- /menu footer buttons -->
              </div>
            </div>

            {% block top_navi %}
                <!-- top navigation -->
                <div class="top_nav">
                  <div class="nav_menu">
                    <nav>
                      <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                      </div>

                      <ul class="nav navbar-nav navbar-right">
                        <li class="">
                          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            <img src="images/img.jpg" alt="">Options
                            <span class=" fa fa-angle-down"></span>
                          </a>
                          <ul class="dropdown-menu dropdown-usermenu pull-right">
                            <li><a href="{% url 'log_in:userloginpagea' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                          </ul>
                        </li>
                      </ul>
                    </nav>
                  </div>
                </div>
                <!-- /top navigation -->
            {% endblock %}
            <div class="right_col" role="main">
              <!-- top tiles -->
                {% block top_tiles %}
              <div class="row tile_count">
                <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                  <span class="count_top"><i class="fa fa-user"></i> Total Users</span>
                  <div class="count">2500</div>
                  <span class="count_bottom"><i class="green">4% </i> From last Week</span>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                  <span class="count_top"><i class="fa fa-clock-o"></i> Average Time</span>
                  <div class="count">123.50</div>
                  <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>3% </i> From last Week</span>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                  <span class="count_top"><i class="fa fa-user"></i> Total Males</span>
                  <div class="count green">2,500</div>
                  <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                  <span class="count_top"><i class="fa fa-user"></i> Total Females</span>
                  <div class="count">4,567</div>
                  <span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>12% </i> From last Week</span>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                  <span class="count_top"><i class="fa fa-user"></i> Total Collections</span>
                  <div class="count">2,315</div>
                  <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                  <span class="count_top"><i class="fa fa-user"></i> Total Connections</span>
                  <div class="count">7,325</div>
                  <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
                </div>
              </div>
          <!-- /top tiles -->
            {% endblock %}


            {% block main_content %}

                  <div class="col-md-6">
                    <h3>Welcome <small>Home Page</small></h3>
                  </div>

            {% endblock %}
        <!-- /page content -->

            </div>
          {% endblock %}
    </div>
    </div>
{% endblock %}


<!-- jQuery -->
    <script src="/static/js/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/static/js/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/static/js/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="/static/js/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="/static/js/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="/static/js/bootstrap-progressbar.min.js"></script>

    <!-- Flot -->
    <script src="/static/js/jquery.flot.js"></script>
    <script src="/static/js/jquery.flot.pie.js"></script>
    <script src="/static/js/jquery.flot.time.js"></script>
    <script src="/static/js/jquery.flot.stack.js"></script>
    <script src="/static/js/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="/static/js/jquery.flot.orderBars.js"></script>
    <script src="/static/js/jquery.flot.spline.min.js"></script>
    <script src="/static/js/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="/static/js/date.js"></script>


<!-- Custom Theme Scripts -->
    <script src="/static/js/custom.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>

      {% block extra_foot_js %}{% endblock %}
</body>
</html>