application/configs/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('log_in/', include('log_in.urls')),
    path('admin/', admin.site.urls),
]

application/log_in/urls.py
from django.urls import path

from . import views

app_name = 'log_in'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('admin/add', views.MyuserCreateView.as_view(), name='add_admin'),
    path('admin/update/<int:id>', views.MyuserUpdateView.as_view(), name='update_admin'),
    path('admin/delete', views.deleteadmin, name='delete_admin'),
    path('admin/profile', views.admin_profile, name='admin_profile'),
    path('admin/activities', views.activities_admin, name='activities_admin'),
    path('adminlist/', views.admin_users_list, name='admin_users_list'),
    path('adminlist/data', views.admin_users_list_data, name='admin_users_list_data'),
    path('user/add', views.UserCreate, name='add_user'),
    path('user/model', views.ModelTrain, name='model_train'),
    path('user/model/train', views.TrainingModel, name='training_model'),
    path('user/model/collect', views.CollectDataset, name='collectdataset'),
    path('user/update/<int:id>', views.UserUpdate, name='update_user'),
    path('user/delete', views.deleteuser, name='delete_user'),
    path('userlist/', views.users_list, name='users_list'),
    path('userlist/data', views.users_list_data, name='users_list_data'),
    path('log_out/', views.log_out, name='log_out'),
    path('password/change', views.password_change, name='password_change'),
    path('password/reset/', views.password_reset, name='password_reset'),
    path('password/reset/update/', views.password_reset_using_token, name='password_reset_using_token'),
    path('adminlog', views.LoginLogss, name='log_in'),
    path('user/home', views.UserLoginPageB, name='userloginpageb'),
    path('', views.UserLoginPageA, name='userloginpagea'),
]

application/log_in/forms.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import validate_email
from django.forms import ModelForm
from django import forms
from django.db import models
from django.utils import timezone
import datetime
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from .models import Myuser, LoginLogs, UserData
import re
from django.contrib.auth.hashers import make_password
from django.contrib.auth import get_user_model

def lower_error(password):
    return re.search(r"[a-z]", password)

def symbol_error(password):
    return re.search(r"[!@$&]", password)

def upcase_error(password):
    return re.search(r"[A-Z]", password)

def digit_error(password):
    return re.search(r"\d", password)

class UserDataForm(ModelForm):
    class Meta:
        model=UserData
        fields = ['lockerno','username']

class UserLoginA(ModelForm):
    class Meta:
        model=UserData
        fields = ['lockerno']

class MyuserForm(ModelForm):
    password = forms.CharField(max_length=100, widget=forms.PasswordInput())
    class Meta:
        model=get_user_model()
        fields = ['username','email','password']

    def __init__(self, *args, **kwargs):
        self.logged_admin = kwargs.pop('logged_admin')  # accessing the request.user in current request coming from view file
        super(MyuserForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(MyuserForm, self).save(commit=False)
        if instance.pk is None:
            instance.date_joined = datetime.datetime.now()
            instance.updated_on = datetime.datetime.now()
            instance.created_by_id = self.logged_admin
            instance.updated_by_id = self.logged_admin
            instance.password = make_password(self.cleaned_data['password'])
        else:
            instance.updated_on = datetime.datetime.now()
            instance.updated_by_id = self.logged_admin
            instance.password = make_password(self.cleaned_data['password'])

        if commit:
            instance.save()
        return instance

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            validate_email(email)
        except:
            raise forms.ValidationError("This is not a valid email")
        return email

    def clean_password(self):
        password = self.cleaned_data['password']
        if len(password)<8 or lower_error(password) is None or upcase_error(password) is None or digit_error(password) is None or symbol_error(password) is None :
            raise forms.ValidationError(
                     "{} is invalid, must have minimum 8 characters, 1 uppercase, 1 lowercase, 1 special character and 1 digit should be present".format(password))
        else:
            return password


    # def clean_password(self):
    #     password = self.cleaned_data['password']
    #     print(password)
    #     try:
    #         re.search(r'[A-Za-z0-9@#$%^&+=]{8,20}', password)
    #         raise forms.ValidationError(
    #             "{} is invalid, must have 8 characters in which 1 uppercase, 1 lowercase, 1 special character and 1 digit should be present".format(password))
    #     except:
    #         return password

class LoginLogsForm(ModelForm):
    password = forms.CharField(max_length=100, widget=forms.PasswordInput())
    class Meta:
        model=LoginLogs
        fields = ['email','password']


class OtpVeriForm(ModelForm):
    otp = models.CharField(max_length=6)
    class Meta:
        model=LoginLogs
        fields = ['otp']
    def clean_otp(self):
        otp = self.cleaned_data['otp']
        if len(otp) != 6:
            raise forms.ValidationError(" OTP must be of lenght 6.")
        else:
            return otp



class PasswordResetForm(ModelForm):
    class Meta:
        model=get_user_model()
        fields = ['email']


class PasswordResetWithTokenForm(ModelForm):
    new_password = forms.CharField(max_length=100, widget=forms.PasswordInput())
    retype_newpassword = forms.CharField(max_length=100, widget=forms.PasswordInput())
    class Meta:
        model=get_user_model()
        fields = ['new_password','retype_newpassword']

    def clean_new_password(self):
        new_password = self.cleaned_data['new_password']
        if len(new_password)<8 or lower_error(new_password) is None or upcase_error(new_password) is None or digit_error(new_password) is None or symbol_error(new_password) is None :
            raise forms.ValidationError(
                     "{} is invalid, must have minimum 8 characters, 1 uppercase, 1 lowercase, 1 special character and 1 digit should be present".format(new_password))
        else:
            return new_password


class PasswordChangeForm(ModelForm):
    old_password = forms.CharField(max_length=100, widget=forms.PasswordInput())
    new_password = forms.CharField(max_length=100, widget=forms.PasswordInput())
    retype_newpassword = forms.CharField(max_length=100, widget=forms.PasswordInput())
    class Meta:
        model=get_user_model()
        fields = ['old_password','new_password','retype_newpassword']

    def clean_new_password(self):
        new_password = self.cleaned_data['new_password']
        if len(new_password)<8 or lower_error(new_password) is None or upcase_error(new_password) is None or digit_error(new_password) is None or symbol_error(new_password) is None:
            raise forms.ValidationError(
                "{} is invalid, must have minimum 8 characters, 1 uppercase, 1 lowercase, 1 special character and 1 digit should be present".format(new_password))
        else:
            return new_password

application/log_in/views.py
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from .models import Myuser, LoginLogs, UserData
from .forms import MyuserForm, LoginLogsForm, UserDataForm, OtpVeriForm, UserLoginA, PasswordResetForm, PasswordResetWithTokenForm, PasswordChangeForm
from django.conf import settings
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseServerError, Http404
from django.urls import reverse
from django.contrib.auth import get_user_model
import random, string
from django.core.mail import send_mail
from django.http import JsonResponse
from django.core import signing
from django.contrib import messages
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.contrib.sessions.models import Session
from django.contrib.auth import update_session_auth_hash
from django.utils.timezone import utc
from django.db.models import Q

User = get_user_model()
import datetime
import time
def index(request):
    return render(request, 'log_in/index.html')

def LoginLogss(request):

    if  request.user.is_authenticated:
        return redirect('log_in:admin_profile')

    else:
        if request.method == 'POST':
            form = LoginLogsForm(request.POST)
            if form.is_valid():
                try:
                    user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password'])
                    if user:
                        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
                        if x_forwarded_for:
                            ip = x_forwarded_for.split(',')[0]
                        else:
                            ip = request.META.get('REMOTE_ADDR')
                        ide = User.objects.get(id=user.id)
                        ide.password_reset_token = None
                        ide.save()
                        obj = LoginLogs.objects.filter(email=form.cleaned_data['email']).latest('id')

                        # print('----------------id----------------',obj.id)
                        if obj.login_time and not obj.logout_time:
                                messages.error(request, 'Already logged in,log out from there to continue.')
                                return redirect('log_in:log_in')
                        else:
                            raise LoginLogs.DoesNotExist
                    else:
                        messages.error(request, 'Invalid Email OR Password')
                        return redirect('log_in:log_in')

                except LoginLogs.DoesNotExist:
                    o = LoginLogs(ip_address=ip,
                                  user_id=ide,
                                  logintry_time=datetime.datetime.now().isoformat(),
                                  agent=request.META['HTTP_USER_AGENT'],
                                  email=form.cleaned_data['email'],
                                  password=make_password(form.cleaned_data['password']),
                                  otp_verified=1,
                                  login_time = datetime.datetime.now().isoformat(),
                                  otp=''.join(
                                      random.choice(
                                          string.ascii_uppercase + string.ascii_lowercase + string.digits)
                                      for i
                                      in range(6))

                                  )
                    o.save()
                    # check = LoginLogs.objects.get(id=request.session['user.id'], email=user.email, otp=user.otp)
                    # if check:
                    obj = LoginLogs.objects.filter(email=form.cleaned_data['email']).latest('id')
                    request.session['idid'] = obj.id
                    login(request, user)
                    return redirect('log_in:admin_profile')


                except Exception as e:
                    print("Excpeth ", e)
                    return HttpResponseServerError(
                        'Some error occured during saving the data. Please try later or contact your administrator.')
        else:
            form = LoginLogsForm()
        return render(request, 'log_in/log_in.html', {'form': form})

@login_required
def admin_profile(request):
    user = User.objects.get(id=request.user.id)
    all_activities = LoginLogs.objects.filter(user_id=user.id)
    return render(request, 'log_in/admin_users_profile.html', {'object': all_activities, 'id': user.id, 'username': user.username, 'email': user.email })

@login_required
#To view the lists of ADMINS
def admin_users_list(request):
    return render(request, 'log_in/admin_users_list.html',{'admin':request.user.email})


@login_required
def admin_users_list_data(request):
    if request.method == 'GET':
        draw = int(request.GET.get('draw', 1))
        queryset_and_total_count = admin_user_get_queryset_and_count(request)
        total_count = queryset_and_total_count.get('total_count')
        queryset = queryset_and_total_count.get('queryset')
        response_data = [{
            'id': user.id,
            'username': user.username,
            'email': user.email,
            'password': user.password,
            'is_active': user.is_active,
            'date_joined': user.date_joined,
            'updated_on': user.updated_on,
            'created_by': user.created_by_id,
            'updated_by': user.updated_by_id,
            # 'filename': name.filename,
        } for user in queryset]
        return JsonResponse(
            {'draw': draw, 'recordsTotal': total_count, 'recordsFiltered': total_count, 'data': response_data})
    else:
        return JsonResponse({})

def admin_user_get_queryset_and_count(request):
    start = int(request.GET.get('start', 0))
    length = int(request.GET.get('length', 10))
    total_count = User.objects.all()
    queryset = User.objects.all()
    total_count = total_count.count()


    order_column = request.GET.get('order[0][column]', None)
    if order_column == None:
        arguments='id'
    else:
        field = request.GET.get('columns['+order_column+'][data]', None)
        order = request.GET.get('order[0][dir]', None)
        if order == 'asc':
            arguments = field
        else:
            arguments = "-" + field


    search = request.GET.get('search[value]', None)
    if search:
        queryset = queryset.order_by(arguments).filter(Q(email__icontains=search)|Q(username__icontains=search))[start:length + start]
    else:
        queryset = queryset.order_by(arguments)[start:length + start]
    return {'queryset': queryset, 'total_count': total_count}


class MyuserCreateView(generic.CreateView):
    # Add new Admin
    queryset = Myuser.objects.all()
    template_name = 'log_in/add_admin.html'
    context_object_name = 'form'
    form_class = MyuserForm

    def form_valid(self, form):
        try:
            self.object = form.save(commit=True)
            return HttpResponseRedirect(reverse('log_in:admin_users_list'))
        except Exception as e:
            print("Excpeth ", e)
            return HttpResponseServerError(
                'Some error occured during saving the data. Please try later or contact your administrator.')

    def get_form_kwargs(self):
        kwargs = super(MyuserCreateView, self).get_form_kwargs()
        kwargs.update({'logged_admin': self.request.user.id})
        return kwargs

class MyuserUpdateView(generic.UpdateView):
    #Update Admin
    model = Myuser
    queryset = Myuser.objects.all()
    form_class = MyuserForm
    pk_url_kwarg = 'id'
    template_name = 'log_in/update_admin_user.html'
    context_object_name = 'form'

    def form_valid(self, form):
        try:
            self.object = form.save(commit=True)
            update_session_auth_hash(self.request, self.object)
            return HttpResponseRedirect(reverse('log_in:admin_users_list'))
        except Exception as e:
            print("Excpeth ", e)
            return HttpResponseServerError(
                'Some error occured during saving the data. Please try later or contact your administrator.')

    def get_form_kwargs(self):
        kwargs = super(MyuserUpdateView, self).get_form_kwargs()
        kwargs.update({'logged_admin': self.request.user.id})
        return kwargs

@login_required
def deleteadmin(request):
    #To Delete the Admin
    user_id = request.GET.get('user_id', None)
    instance = User.objects.get(pk=int(user_id))
    instance.delete()
    data = {'qwe': 'asd'}
    return JsonResponse(data)

@login_required
def activities_admin(request):
    #View Activities of Admin
    #print("in view_logs_list")
    user_id = request.GET.get('user_id', None)
    #print(user_id)
    obj = User.objects.get(id=user_id)
    #check = LoginLogs.objects.get(email=request.user.email, user_id=user_id)
    all_activities = LoginLogs.objects.filter(user_id=user_id)
    # print(check.email,check.id)
    # #print(check)
    return render(request, 'log_in/view_logs_list.html', {'object': all_activities, 'email' : obj.email})

@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.POST)
        if form.is_valid():
            oldpassword = form.cleaned_data['old_password']
            newpassword = form.cleaned_data['new_password']
            renewpassword = form.cleaned_data['retype_newpassword']
            if not request.user.check_password(oldpassword):
                messages.error(request, 'Enter correct Old Password.')
                return redirect('log_in:password_change')
            else:
                if newpassword != renewpassword:

application/log_in/templates/log_in/admin_users_list.html
{% extends "profile.html" %}
{% block title %}
Users Database
{% endblock %}
{% block top_tiles %}{% endblock %}

{% block main_content %}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Admin Management</h2>
                <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="clearfix">
                    <div class="pull-right tableTools-container"></div>
                </div>
                <div class="table-header">
                    Hey,<br/> {{ admin }}
                    <div class="pull-right"><a href="{% url 'log_in:add_admin' %}" class="btn btn-white btn-sm " style="margin-left:-120px">Add Admin</a></div>
                </div>

                <!-- div.dataTables_borderWrap -->
                <div>
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th>Serial No.</th>
                            <th>User Id</th>
                            <th>User Name</th>
                            <th>Email</th>
                            <th>Is Active</th>
                            <th>Created On</th>
                            <th>Updated On</th>
                            <th>Created By</th>
                            <th>Updated By</th>
                            <th>Update</th>
                        </tr>
                        </thead>

                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<p id="a"></p>
{% endblock %}

{% block extra_foot_js %}
<script>
    var data_url  =  "{% url 'log_in:admin_users_list_data' %}";
    var tableOption = {
        name: "AdminsList",
        serverSide: true,
        "order": [],
        "pageLength":10,
        dom: "<'row'<'col-xs-6'l><'col-xs-6'f>>t<'row'<'col-xs-6'i><'col-xs-6'p>>",
        ajax: {
            url: data_url ,
            type: 'GET',
        },
        columnDefs: [
            {
            "targets": -1,
            "render": function (data, type, full, meta) {
                console.log(full);
                var html = "<div class='hidden-sm hidden-xs action-buttons'>";
                    html += "<button id='delete' class='btn btn-xs btn-success' data-id=" + full.id + ">Delete!</button>";
                    html += "<button id='view' class='btn btn-xs btn-success' data-id=" + full.id + ">View Logs</button>";
                    html += "<button id='update' class='btn btn-xs btn-success' data-id=" + full.id + ">Edit</button>";
                    html+= "</div>";
                return html;
            }
        },
       {
            "targets": -2,
            "render": function (data, type, full, meta) {
                return data;
            }
        }],
        columns: [
            { data: null,orderable: false,className: "text-center" },
            { data: "id", className: "text-center" },
            { data: "username", className: "text-center" },
            { data: "email", className: "text-center" },
            { data: "is_active", className: "text-center" },
            { data: "date_joined", className: "text-center" },
            { data: "updated_on", className: "text-center" },
            { data: "created_by", className: "text-center" },
            { data: "updated_by", className: "text-center" },
            { data: null,orderable:false, className: "text-center" },
        ],

        "drawCallback": function (settings) {
            var api = new $.fn.dataTable.Api(settings);
            api.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                var page = api.page();
                var len = api.page.len();
                cell.innerHTML = (page*len) + (i + 1);
                api.cell(cell).invalidate('dom');
            });
        }
    };

    $(document).ready(function(){
     var data_table = $("table").DataTable(tableOption);


     $("table").on("click", "#delete", function(event){
             id = $(this).data('id');
            $.ajax({
                url: "/log_in/" + "admin/delete"  + "?user_id=" + id ,
                type : 'get',
                success: function (data) {
                    location.reload()
                    }
                })
            });
     $("table").on("click", "#view", function(event){
             id = $(this).data('id');
           window.location.assign("{% url 'log_in:activities_admin' %}?user_id="+id)
            });
     $("table").on("click", "#update", function(event){
            id = $(this).data('id');
          window.location.assign("{% url 'log_in:update_admin' id=12 %}".replace('12', id))
            });
    });


</script>
{% endblock %}

application/log_in/templates/log_in/dataset_and_training_of_model.html
{% extends "profile.html" %}
{% block title %}
Add User
{% endblock %}
{% block top_tiles %}{% endblock %}

{% block main_content %}
<div class="clearfix"></div>
<div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Dataset Collection AND Model Training</h2>
                      <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <br/><br/><br/><br/>
                            <h3><center><li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li></center></h3>
                            {% endfor %}
                        </ul>
                        {% endif %}
                      <div class="login_wrapper">
                        <div class="animate form login_form">
                          <section class="login_content">
                            <form method="post" action="{% url 'log_in:users_list' %}">
                              {% csrf_token %}
                              <div>
                                <a href="{% url 'log_in:collectdataset' %}" class="btn btn-success">COLLECT DATASET</a><br><br>
                                <a href="{% url 'log_in:training_model' %}" class="btn btn-success">TRAIN MODEL</a><br><br><br>
                              </div>
                              <div>
                                  <button type="submit" class="btn btn-success">Submit</button>
                              </div>
                              <div class="clearfix"></div>
                              <div class="separator">
                                <div class="clearfix"></div>
                                <br/>
                              </div>
                            </form>
                          </section>
                        </div>
                      </div>
                  </div>
                </div>
              </div>
            </div>
{% endblock %}

application/log_in/templates/log_in/log_in.html
{% extends "layout.html" %}
{% block title %}
Login
{% endblock %}

{% block body %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <br/><br/><br/><br/>
    <h3><center><li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li></center></h3>
    {% endfor %}
</ul>
{% endif %}
<body class="login">
    <div>
      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form method="post" action="{% url 'log_in:log_in' %}">
              {% csrf_token %}
              <h1>Admin Login Form</h1>
              <div>
                {% for field in form %}
                          <label>{{ field.label_tag }} <span class="required">*</span>
                        </label>
                          <div>
                          {{ field }}
                        </div>
                          {% endfor %}
              </div>
              <div>
                <button type="submit" class="btn btn-success">Submit</button>
                <a class="reset_pass" href="{% url 'log_in:password_reset' %}">Lost your password?</a>
              </div>
              <div class="clearfix"></div>
              <div class="separator">
                <div class="clearfix"></div>
              </div>
            </form>
          </section>
        </div>
      </div>
    </div>
  </body>
{% endblock %}

application/log_in/templates/log_in/users_list.html
{% extends "profile.html" %}
{% block title %}
Users Database
{% endblock %}
{% block top_tiles %}{% endblock %}

{% block main_content %}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>User Management</h2>
                <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="clearfix">
                    <div class="pull-right tableTools-container"></div>
                </div>
                <div class="table-header">
                    Hey,<br/> {{ admin }}
                    <div class="pull-right"><a href="{% url 'log_in:add_user' %}" class="btn btn-white btn-sm " style="margin-left:-120px">Add User</a></div>
                </div>
                <!-- div.dataTables_borderWrap -->
                <div>
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th>Serial No.</th>
                            <th>User Id</th>
                            <th>Locker Number</th>
                            <th>User Name</th>
                            <th>Folder Name</th>
                            <th>Update</th>
                        </tr>
                        </thead>

                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<p id="a"></p>
{% endblock %}

{% block extra_foot_js %}
<script>
    var data_url  =  "{% url 'log_in:users_list_data' %}";
    var tableOption = {
        name: "UsersList",
        serverSide: true,
        "order": [],
        "pageLength":10,
        dom: "<'row'<'col-xs-6'l><'col-xs-6'f>>t<'row'<'col-xs-6'i><'col-xs-6'p>>",
        ajax: {
            url: data_url ,
            type: 'GET',
        },
        columnDefs: [
            {
            "targets": -1,
            "render": function (data, type, full, meta) {
                console.log(full);
                var html = "<div class='hidden-sm hidden-xs action-buttons'>";
                    html += "<button id='delete' class='btn btn-xs btn-success' data-id=" + full.id + ">Delete!</button>";
                    html += "<button id='update' class='btn btn-xs btn-success' data-id=" + full.id + ">Edit</button>";
                    html+= "</div>";
                return html;
            }
        },
       {
            "targets": -2,
            "render": function (data, type, full, meta) {
                return data;
            }
        }],
        columns: [
            { data: null,orderable: false,className: "text-center" },
            { data: "id", className: "text-center" },
            { data: "lockerno", className: "text-center" },
            { data: "username", className: "text-center" },
            { data: "foldername", className: "text-center" },
            { data: null,orderable:false, className: "text-center" },
        ],

        "drawCallback": function (settings) {
            var api = new $.fn.dataTable.Api(settings);
            api.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                var page = api.page();
                var len = api.page.len();
                cell.innerHTML = (page*len) + (i + 1);
                api.cell(cell).invalidate('dom');
            });
        }
    };

    $(document).ready(function(){
     var data_table = $("table").DataTable(tableOption);


     $("table").on("click", "#delete", function(event){
             id = $(this).data('id');
            $.ajax({
                url: "/log_in/" + "user/delete"  + "?user_id=" + id ,
                type : 'get',
                success: function (data) {
                    location.reload()
                    }
                })
            });
     $("table").on("click", "#update", function(event){
            id = $(this).data('id');
          window.location.assign("{% url 'log_in:update_user' id=12 %}".replace('12', id))
            });
    });


</script>
{% endblock %}